os: linux
dist: focal
group: edge
language: python
env: 
  - COSIGN_EXPERIMENTAL=1
services:
  - docker
jobs:
  include:
    - stage: "sleep 109"
      script: docker build . -t docker-test
keys:
  - Art
