os: linux
dist: focal
language: python
addons: 
  - sbom:
      on:
        branch: sbom_one_fix
        pr: true
        condition: os = linux
      run_phase: before_script
      output_format: spdx-json
      output-dir: 'python'
  - mariadb
script:
  - cd python
  - pip install -r requirements.txt
  - cd..
  - python hello_world.py
