os: linux
dist: focal
group: edge
language: python
env: 
  - COSIGN_EXPERIMENTAL=1
services:
  - docker
jobs:
  include:
    - stage: "sleep 109"
      script: cosign
before_install: 
- debian:buster-slim
- RUN touch /file.txt  
- docker build . -t docker-test
keys:
  - Art
